### ISSUE TITLE
načítáš aji mezery

### ISSUE THREAD

**Issue by vlccek** [VUT-FIT-team/Lua-interpret#10]
value u identifier obsahuje aji mezery. Nevím jestli to tam chceme, ale myslím že ne ?

**Comment by ENIACx64** [comment]
no ale já potom posouvám nulový znak, takže ta mezera by tam být neměla

**Comment by vlccek** [comment]
![image](https://user-images.githubusercontent.com/43584052/139526676-340be80c-8798-439d-810b-2036fe302494.png)
Toto je stav před free v debugeru.

**Comment by vlccek** [comment]
![image](https://user-images.githubusercontent.com/43584052/139526757-c1048156-c173-452c-ac98-f0b93b0c54cd.png)
Ještě přidávám aji jak vypadá struktura

**Comment by ENIACx64** [comment]
to je divné... když posunu nulový znak ještě o jednu pozici doleva, tak už mi mizí poslední znak řetězce...

**Comment by ENIACx64** [comment]
done
