### ISSUE TITLE
Nevím co se děje

### ISSUE THREAD

**Issue by vlccek** [VUT-FIT-team/Lua-interpret#11]
https://github.com/VUT-FIT-team/Lua-interpret/blob/ed5114f37da3490650ea826c3988e183cf084bd9/lex.c#L941

Hodili by se komentáře co se děje. Předpokládám že se zbavuješ uvozovek ? Asi ? nevím

**Comment by vlccek** [comment]
týký se to celého obsahuj case

**Comment by ENIACx64** [comment]
komentáře přibudou, no worries... jen je to všechno zatím rozdělané a prone to change
