### ISSUE TITLE
Nevyužítí potencionálu strtol

### ISSUE THREAD

**Issue by vlccek** [VUT-FIT-team/Lua-interpret#12]
https://github.com/VUT-FIT-team/Lua-interpret/blob/ed5114f37da3490650ea826c3988e183cf084bd9/lex.c#L960

Strtol umožnuje detekovat že se nepovedl převod čísla. Chytit ifem vypsat do std_err

**Comment by vlccek** [comment]
Jinak chválím za strtol, lepší jak atoi :D

**Comment by ENIACx64** [comment]
noted, přibude to

**Comment by AntoninJarolim** [comment]
@ENIACx64 Kdyžtak zčekni jestli je tohle ok

když to bude překládat např "sracka", vrátí to 0 a pošleš to jako int 0 nebo se zdetekuje chyba?
jinak tenhle išus pls zavři

**Comment by ENIACx64** [comment]
asi tam udělám prostě error

**Comment by ENIACx64** [comment]
ok, zavírám
