### ISSUE TITLE
Lex nic nedělá s `(` a `)`

### ISSUE THREAD

**Issue by Kiznoh** [VUT-FIT-team/Lua-interpret#14]

**Comment by AntoninJarolim** [comment]
existuje case i token pro zavorky, ale nikdy ho lex nevrací

**Comment by ENIACx64** [comment]
jo, musím ještě přidělat závorky... noted

**Comment by ENIACx64** [comment]
Mělo by to fungovat, zkoušel jsem to testovat. Kdyby někdo z vás objevil nějaký bug, dejte prosím vědět - prozatím zavírám issue
