### ISSUE TITLE
Detekce klíčových slov

### ISSUE THREAD

**Issue by Kiznoh** [VUT-FIT-team/Lua-interpret#15]
nebylo by tolepší podle 5. prezentace?
![obrazek](https://user-images.githubusercontent.com/11771435/140976105-0cad6a78-356d-4576-89be-d30c0287138e.png)

**Comment by ENIACx64** [comment]
Dodal jsem dočasné řešení, které teoreticky tenhle issue řeší, ale je dost prasácké, takže zatím jen temporary - účel to ale plní. Uzavírám tenhle issue a vytvořím si na to specificky nový, aby mě to nemátlo, že jsem se to ještě nepokoušel spravit.
