### ISSUE TITLE
Chybí token pro : a , 

### ISSUE THREAD

**Issue by vlccek** [VUT-FIT-team/Lua-interpret#18]
Jednoduše. Chybí nám to aby nám fungovala gramatiak

**Comment by AntoninJarolim** [comment]
lexikální analyzátor potřebuje vědět že na vstupu přišla dvojtečka i čarka, například při parsování funkcí nebo množiny návrotových typů se bez toho neobejdeme

**Comment by AntoninJarolim** [comment]
Přidal jsem tokeny, je třeba je někdy vracet.

**Comment by ENIACx64** [comment]
noted, podívám se na to

**Comment by ENIACx64** [comment]
hotovo, zavírám
