### ISSUE TITLE
Lex nemá tokeny (klíčová slova) pro `for`, `repeat`, `until` a `break`

### ISSUE THREAD

**Issue by Kiznoh** [VUT-FIT-team/Lua-interpret#19]
je to součásti rozšíření, které budeme implementovat. 
aby se nemuselo předělávat FSM, bylo by dobré to implementovat podle #15.

**Comment by AntoninJarolim** [comment]
+ break

**Comment by ENIACx64** [comment]
Fixed, zavírám
