### ISSUE TITLE
Realloc po jedné

### ISSUE THREAD

**Issue by vlccek** [VUT-FIT-team/Lua-interpret#8]
Není dobrý nápad dopřávat si pamět po jedné. Vzhledem k tomu že přidělení paměti je extrémě časově drahá operace. Nalokuj nějákou rozumnou hodnotu a pak dvojnásobek.  
https://github.com/VUT-FIT-team/Lua-interpret/blob/ed5114f37da3490650ea826c3988e183cf084bd9/lex.c#L287

**Comment by ENIACx64** [comment]
done
