### ISSUE TITLE
Realloc do stejné proměné kterou chceš aby byla větší

### ISSUE THREAD

**Issue by vlccek** [VUT-FIT-team/Lua-interpret#9]
https://github.com/VUT-FIT-team/Lua-interpret/blob/ed5114f37da3490650ea826c3988e183cf084bd9/lex.c#L287

Pokud chceš mít čistý kod tak musíš ukládat výsledek realocu do mezi proměné. Například takto:
propojuji s #8 
```c
if (potřebuju víc paměti.){
  sizeOfBuffer = sizeOfBuffer * 2;
  if ((char* newbuffer = realloc(buffer, sizeof(char) * (sizeofBuffer)) == NULL )){
    free(buffer)
    exit(99); // cokoliv to je jedno...
  }
buffer = newBuffer;
}
```

Jinak nemůžeš v případě neuspěchu free na starou promeněnou

**Comment by ENIACx64** [comment]
done
